# Generated by Django 6.0.2 on 2026-02-23 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=100, unique=True)),
                ('percentuale', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_scadenza', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
